-- coclocar em uso o banco de dados
use sistema_pedidos

exec sp_help TB_EMPREGADO
-- ADICONAR COLUNA CPF NA TABELA TB_EMPREGADO
ALTER TABLE TB_EMPREGADO
ADD CPF BIGINT NOT NULL
-- SEMPRE SERÁ ADICONADO NA ULTIMA POSIÇÃO, NAO É POSSIVEL COLOCAR EM UMA ORDEM ESPECIFICA
-- CONSULTAR  A TABELA
SELECT * FROM TB_EMPREGADO

