-- colocar em uso o banco de dados

use PEDIDOS;

/*
COMANDO SELECT
SELECT *(TODAS AS COLUNAS) FROM NOME_TABELAS
*/
-- EXSBIR COLUNAS E TABELAS QU EXISTEM NO BANCO EM USO
SELECT * 
FROM SYS.tables

-- FUNÇÃO PARA RETORNA A DTA E HORA DO SERVIDOR
SELECT GETDATE()

