-- CONSTRAINT CHECK
EXEC SP_HELP TB_CARGO
-- CHECK PARA COLUNA SALARIO() NAO PODE SER NEGATIVA
ALTER TABLE TB_CARGO
ADD CONSTRAINT CK_CARGO_SALARIOINIC CHECK(SALARIO_INIC>0)

-- CONSTRAIT UNIQUE
EXEC SP_HELP TB_EMPREGADO
-- CLUNA COF NAO PODE REPETIR 
ALTER TABLE  TB_EMPREGADO
ADD CONSTRAINT UQ_EMPREGADO_CPF UNIQUE(CPF)

