-- constraint check na coluna sindicalizado(s ou n)

alter table TB_EMPREGADO
ADD 
CONSTRAINT CL_EMPREGADO_SIND CHECK(SINDICALIZADO IN ('s','n'))

EXEC SP_HELP TB_EMPREGADO

ALTER TABLE TB_EMPREGADO
ADD CONSTRAINT DF_EMPREGADO_SIND DEFAULT('s') FOR SINDICALIZADO