 -- IDENTITY AUTONUMERAÇÃO

 CREATE TABLE TB_DEPENDENTES(
 COD_DEPENDENTE INT IDENTITY(1,1),
 CODFUN INT NULL,
 NOME CHAR(50) NOT NULL,
 DATA_NASCIMENTO DATE NOT NULL
 )

 -- SEINTAXE IDENTITY IDENTITY(NUMERO QUE INICIA, NUMERO QUE QUER QUE INCREMENTE TIPO 2 EM 2, 1 EM 1)
 EXEC SP_HELP TB_DEPENDENTES
 -- COLOCAR CHAVES PRIMARIA E ESTRANEIRA
 ALTER TABLE TB_DEPENDENTES
 ADD 
 CONSTRAINT PK_DPEENDENTES_CODDEP PRIMARY KEY(COD_DEPENDENTE)
 ,CONSTRAINT FK_DEPENDENTES_CODFUN FOREIGN KEY(CODFUN)
 REFERENCES TB_EMPREGADO(CODFUN)
