-- VIZUALIZAR ESTRUTURA 
EXEC sp_help TB_EMPREGADO
-- APAGAR COLUNA CPF
ALTER TABLE TB_EMPREGADO
DROP COLUMN CPF
-- CRIAR COLUNA NA TABELA
ALTER TABLE TB_EMPREGADO
ADD CPF INT NOT NULL
-- ALTERAR TIPO DE DADOS DA COLUNA
ALTER TABLE TB_EMPREGADO
ALTER COLUMN CPF BIGINT NOT NULL

