-- CRIAR A TABELA EMPREGADO
-- COINSTRAINT DE CHAVE PRIMERIA PARA A CODFUN
-- COINSTRAINT DE COD_DEPTO E COD_CARGO

create table TB_EMPREGADO(
CODFUN int not null,
NOME VARCHAR(35) NOT NULL,
NUM_DEPEND SMALLINT NOT NULL,
DATA_NASCIMANTO DATETIME NOT NULL,
COD_DEPTO INT NOT NULL,
COD_CARGO INT NOT NULL,
DATA_ADMISSAO DATETIME NOT NULL,
SALARIO NUMERIC(18,2),
PREMIO_MENSAL NUMERIC(10,2) NOT NULL,
SINDICALIZADO CHAR(1) NOT NULL,
OBS TEXT NOT NULL,
FOTO IMAGE NOT NULL,
COD_SUPERVISOR INT NOT NULL,
CONSTRAINT PK_CODFUN PRIMARY KEY(CODFUN)

) 
-- NUEMRIC(5,2) EXEMPLO 
-- _ _ _ ,_ _ |  